### ISSUE TITLE
[ERROR]     'dependencies.dependency.artifactId' for org.eclipse.swt:${swt.artifactId}:jar with value '${swt.artifactId}' does not match a valid id pattern. @ line 105, column 16

### ISSUE THREAD

**Issue by hamidrezaabroshan** [Xianguang-Zhou/swt-maven-repository#1]
I copied profiles and dependencies as you said, but when run my project with maven install from eclipse ide, it give me that error. I'm using jdk 8 and maven 3.6 and eclipse ide 2019 thanks.

**Comment by Xianguang-Zhou** [comment]
Please put "`<profiles>...</profiles>`" before "`<dependencies>...</dependencies>`".

**Comment by hamidrezaabroshan** [comment]
[ERROR]     Non-parseable POM D:\eclipse-workspace\Cinema\pom.xml: Duplicated tag: 'profiles' (position: START_TAG seen ...</repositories>\r\n\t<profiles>... @96:12)  @ line 96, column 12 -> [Help 2]
First, I added <profiles>... </profiles>
Because of this error, I moved <dependencies>...</dependencies> to profile section but it did not help too.
thanks.

**Comment by Xianguang-Zhou** [comment]
Please look at this example: [pom.xml](../blob/master/pom.xml)

**Comment by hamidrezaabroshan** [comment]
Thanks, I built my pom as same as your example, but it gives that error!
[ERROR]     'dependencies.dependency.artifactId' for org.eclipse.swt:${swt.artifactId}:jar with value '${swt.artifactId}' does not match a valid id pattern. @ line 99, column 16
I copied all of the profiles and all of dependencies with no changes.
only my project name and target are different with your example.
I changed my pom.xml to pom.txt and attached it to this comment.
`		<dependency>
			<groupId>org.eclipse.swt</groupId>
// line 99			<artifactId>${swt.artifactId}</artifactId>
			<version>4.3.2</version>

[pom .xml.txt](https://github.com/Xianguang-Zhou/swt-maven-repository/files/4615487/pom.xml.txt)
		</dependency>`
Thanks very much.
